version: 1.0.{build}
image: Visual Studio 2017 Previewinit:
- ps: >-
    cd "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.14.26428\include"    svn checkout https://github.com/Microsoft/GSL/trunk/include/gsl    cd C:\projects\fireemblem
environment:
  matrix:
   - additional_flags: "/std:c++latest"before_build:
  - set CXXFLAGS=%additional_flags%build:
  verbosity: normal

# Execute script before build
before_build:
 - nuget restore p1\p1.sln

# MSBuild settings
build:
  project: p1\p1.sln
